name: CI

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Dependencies
      run: |
        sudo apt update
        sudo apt install -y libflatpak-dev systemd meson valac
    - name: Build
      env:
        DESTDIR: out
      run: |
        meson build
        ninja -C build
        sudo ninja -C build install

  lint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: elementary/actions/vala-lint@master
